S01US41 - Page vue d'une décision.
WildCodeSchool/202209-orleans-php-project-makesense pull request #109
Opened 2022-12-16 14:11 UTC by toomanyMG

Il n'y a rien dynamique car l'entity décision n'était pas encore créer quand j'ai créer ma branche.

2022-12-16 15:11 UTC, ByZirTox approved these changes

2022-12-19 08:38 UTC, sblondeau requested changes
plutot que Jeanne, met un placeholder neutre, ça gèrera direct le cas où la personne n'a pas mis d'avatar
après pour les icones en svg, tu as bootstrap-icons, mais si tu as vraiment besoin d'en importer des spécifiques via des fichiers, fait un sous dossier icones dans images, ça sera peut-etre plus clair ;-)

2022-12-19 08:38 UTC, sblondeau commented on assets/styles/decisionView.scss
> +    background-color: #3B8AA6;
variable couleur

2022-12-19 08:38 UTC, sblondeau commented on templates/decisions/decisionPage.html.twig
> +				<h1 class="text-secondary text-uppercase fw-bolder fs-4 col-md-8 text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias repudiandae illo voluptate quo sunt. Consectetur p
pas de lorem en dur car c'est administrable. 
Il faut utiliser l'entité Decision et l'afficher depuis la bdd

2022-12-19 08:38 UTC, sblondeau commented on src/Controller/DecisionController.php
> +    #[Route('decision', name: 'app_decision')]
tu dois charger UNE decision en particulier non ? donc manque un id dans ta route, param converter, entity etc

2023-01-02 16:31 UTC, V-Gillet approved these changes

2023-01-02 16:48 UTC, sblondeau requested changes

2023-01-02 16:48 UTC, sblondeau commented on templates/decisions/decisionView.html.twig
> +					<div class="text-uppercase fw-bold py-3">Jeannette Doeatienne</div>
c'est pas plutot qqchose comme {{ decision.author.name }}

2023-01-03 10:42 UTC, ByZirTox commented on templates/decisions/decisionView.html.twig
> +					<div class="text-uppercase fw-bold py-3">Jeannette Doeatienne</div>
Le petit alt pour le référencement :D

2023-01-03 10:54 UTC, toomanyMG commented on templates/decisions/decisionView.html.twig
> +					<div class="text-uppercase fw-bold py-3">Jeannette Doeatienne</div>
On n'a pas encore associé un créateur avec sa décision, faut que je le fasse sur cette US ou on peut fix ça plus tard ?

2023-01-03 11:23 UTC, sblondeau approved these changes

2023-01-03 11:23 UTC, merged