Sp01-Us14  page user acceuil
WildCodeSchool/202209-orleans-php-project-makesense pull request #121
Opened 2022-12-16 15:09 UTC by ByZirTox

2022-12-20 10:33 UTC, toomanyMG submitted a review, later dismissed

2022-12-20 15:47 UTC, sblondeau requested changes

2022-12-20 15:47 UTC, sblondeau commented on assets/styles/PageUserAcceuil.scss
> +.pageUserAcceuil-title {
en anglais les nom de classe, et si possible sans faute :p (accueil en français)

2022-12-20 15:47 UTC, sblondeau commented on src/Controller/ProfilUserController.php
> +            12
passe par une constante plutot que de mettre 12 en dur

2022-12-20 15:47 UTC, sblondeau commented on src/Controller/ProfilUserController.php
> +            'controller_name' => 'ProfilUserController',
contorller_name à virer (c'est l'exemple généré par le maker)

2022-12-20 15:47 UTC, sblondeau commented on src/DataFixtures/DecisionFixtures.php
> +    public const LOOP_COUNT = 100;
DECISION_NUMBER plutot car si tu veux réutiliser ce nombre ailleurs, LOOP_COUNT est pas parlant

2022-12-20 15:47 UTC, sblondeau commented on webpack.config.js
> +    .addStyleEntry('PageUserAcceuil', './assets/styles/PageUserAcceuil.scss')
renommer aussi

2022-12-21 14:39 UTC, ByZirTox commented on src/Controller/ProfilUserController.php
> +            12
Ce n'est pas a moi c'est a valentin

2022-12-21 14:40 UTC, ByZirTox commented on src/DataFixtures/DecisionFixtures.php
> +    public const LOOP_COUNT = 100;
Pareil c'est a valentin

2022-12-21 15:42 UTC, stephaparicio submitted a review, later dismissed

2022-12-21 16:00 UTC, sblondeau requested changes

2022-12-21 16:00 UTC, sblondeau commented on src/Controller/ProfilUserController.php
> +            'controller_name' => 'ProfilUserController',
pas fait

2022-12-21 16:00 UTC, sblondeau commented on src/DataFixtures/DecisionFixtures.php
> +    public const LOOP_COUNT = 100;
tu modifies quand meme

2022-12-21 16:00 UTC, sblondeau commented on webpack.config.js
> +    .addStyleEntry('PageUserAcceuil', './assets/styles/PageUserAcceuil.scss')
à faire

2023-01-02 11:32 UTC, V-Gillet requested changes

2023-01-02 11:32 UTC, V-Gillet commented on assets/styles/PageUserAcceuil.scss
> +@import "_theme";
Tout est déjà importé dans app.scss.

2023-01-02 11:32 UTC, V-Gillet commented on assets/styles/PageUserAcceuil.scss
> +}
Utilises plutôt ça : class="display-5"
Ca correspond à 3rem en bootstrap directement.

2023-01-02 11:32 UTC, V-Gillet commented on assets/styles/PageUserAcceuil.scss
> +}
En faisant ça tu changes toutes la background-color du site entier.

2023-01-02 11:32 UTC, V-Gillet commented on assets/styles/PageUserAcceuil.scss
> +}
Utilises plutôt la balise <main> car on a un système qui permet de modifier le background par cette balise. Dans _theme.scss : 
main{
    padding-block-start :20vh;
}

2023-01-02 11:32 UTC, V-Gillet commented on src/Controller/ProfilUserController.php
> +        );
Elle sert à quoi cette requête dans le ProfilUserController ? :p

2023-01-02 11:32 UTC, V-Gillet commented on src/Controller/ProfilUserController.php
> +            'controller_name' => 'ProfilUserController',
Tu aurais pû supprimer 'controller_name' :D 
C'est le truc par défaut qui est créé en faisant symfony console make:controller

2023-01-02 12:25 UTC, ByZirTox commented on src/Controller/ProfilUserController.php
> +            'controller_name' => 'ProfilUserController',
Je l'avais deja suprrimer :D

2023-01-03 10:02 UTC, V-Gillet approved these changes

2023-01-03 11:20 UTC, sblondeau requested changes
je te laisse refaire cette US plus tard, en la découpant en plusieurs morceaux, comme discuté

2023-01-03 11:20 UTC, sblondeau commented on templates/components/_decisionCards.html.twig
> +				<b>Jane Doe</b>
pas de nom en dur, enlever le Jane Doe pour le moment

2023-01-24 11:26 UTC, closed without merging