S02US11-category
WildCodeSchool/202209-orleans-php-project-makesense pull request #143
Opened 2023-01-04 15:11 UTC by stephaparicio

2023-01-04 15:25 UTC, Zakari-B approved these changes

2023-01-16 14:59 UTC, V-Gillet approved these changes

2023-01-16 14:59 UTC, V-Gillet commented on src/DataFixtures/DecisionFixtures.php
> +            }
Ta branche est assez datée, ça a beaucoup changé ici donc vient me voir pour résoudre les conflits, on va s'éclater :D

2023-01-16 15:04 UTC, V-Gillet approved these changes

2023-01-16 15:49 UTC, sblondeau requested changes

2023-01-16 15:49 UTC, sblondeau commented on migrations/Version20230108123103.php
> +<?php
je ne veux qu'un seul fichier de migration par PR, or tu en as 3-4 là

2023-01-16 16:12 UTC, V-Gillet submitted a review, later dismissed

2023-01-17 08:15 UTC, sblondeau submitted a review, later dismissed

2023-01-18 16:14 UTC, V-Gillet approved these changes

2023-01-19 10:11 UTC, V-Gillet approved these changes

2023-01-19 11:13 UTC, sblondeau requested changes

2023-01-19 11:13 UTC, sblondeau commented on assets/styles/decisionView.scss
> +=======
heureusement que j'ai rouvert suite à la résolution du conflit... 
ça ne doit pas passer ce genre d'erreur de conflit mal résolu, ça se voit ;-)

2023-01-19 11:13 UTC, sblondeau commented on assets/styles/decisionView.scss
> +>>>>>>> a3f43941aa7c611151a75b1bb26728790e2e1a80
et ne pas oublier c"elle là aussi

2023-01-19 14:43 UTC, Ga-Mikael requested changes

2023-01-19 14:43 UTC, Ga-Mikael commented on templates/components/_decisionCards.html.twig
> +
Tu peux le supprimer cela n'existe plus.

2023-01-19 14:43 UTC, Ga-Mikael commented on templates/home/index.html.twig
> +{% endblock %}
La feuille de style decisionView c'est pour la vue d'une décisions. Pas besoin de la faire venir sur home, tu peux utiliser _theme.scss si tu as vraiment besoin.

2023-01-19 14:43 UTC, Ga-Mikael commented on assets/styles/decisionView.scss
> -#timelineGrid {
Si tu supprime ça on va avoir un petit soucis de style 🙃

2023-01-19 15:39 UTC, Ga-Mikael approved these changes

2023-01-19 16:09 UTC, sblondeau submitted a review, later dismissed

2023-01-20 08:26 UTC, Ga-Mikael submitted a review, later dismissed

2023-01-20 08:32 UTC, Ga-Mikael approved these changes

2023-01-20 08:36 UTC, Zakari-B approved these changes

2023-01-20 08:42 UTC, merged