fixed logout and profil routes
WildCodeSchool/202209-orleans-php-project-makesense pull request #154
Opened 2023-01-05 15:47 UTC by V-Gillet

2023-01-05 16:29 UTC, ByZirTox submitted a review, later dismissed

2023-01-06 07:50 UTC, sblondeau requested changes

2023-01-06 07:50 UTC, sblondeau commented on src/Controller/ProfileController.php
> +    #[Route('/myprofile', name: 'app_view_my_profil')]
mon-profil (en français plutot)

2023-01-06 08:29 UTC, Zakari-B approved these changes

2023-01-06 08:29 UTC, merged