S03US03-impacted employees
WildCodeSchool/202209-orleans-php-project-makesense pull request #190
Opened 2023-01-16 11:59 UTC by V-Gillet

2023-01-16 12:59 UTC, toomanyMG approved these changes

2023-01-16 14:38 UTC, sblondeau requested changes

2023-01-16 14:38 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            'decisionRole' => 'impacted'
il va falloire que tu travailles au maximum avec des constantes pour tes roles

2023-01-16 14:38 UTC, sblondeau commented on src/Entity/Interaction.php
> +    #[ORM\Column(length: 45, nullable: true)]
du coup ici faut s'assurer que tu n'aies rien d'autre que les roles que tu autorises https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/cookbook/mysql-enums.html

2023-01-16 15:19 UTC, toomanyMG approved these changes

2023-01-17 08:18 UTC, sblondeau requested changes

2023-01-17 08:18 UTC, sblondeau commented on src/Entity/Interaction.php
> +    public const DECISION_ROLE = ['impacted', 'expert'];
faut que tu travailles ta constante différemment, car là tes valeurs sont en anglais, tu ne peux pas l'afficher facilement dans ta vue. Fais plutot
DECISION_IMPACTED = 'impacté';
DECISION_EXPERT = 'expert';
dans ton Twig tu peux aller chercher des valeurs de constantes si besoin.

2023-01-17 08:18 UTC, sblondeau commented on src/Entity/Interaction.php
> +    public const DECISION_ROLE = ['impacted', 'expert'];
car utliser la key 0 ou 1 n'est pas très lisible je trouve

2023-01-18 13:19 UTC, toomanyMG approved these changes

2023-01-18 14:21 UTC, sblondeau requested changes

2023-01-18 14:33 UTC, V-Gillet commented on src/Controller/DecisionController.php
> +            'decisionRole' => Interaction::DECISION_IMPACTED,
Le mieux serait de trier par prénom d'utilisateur mais je ne vois pas comment faire dans le findBy d'interaction. Je ne suis pas sûr que ça apporte énormément.

2023-01-18 14:59 UTC, toomanyMG approved these changes

2023-01-18 15:56 UTC, sblondeau approved these changes

2023-01-18 15:56 UTC, merged