S03 us58 add impacted employee
WildCodeSchool/202209-orleans-php-project-makesense pull request #227
Opened 2023-01-19 15:36 UTC by V-Gillet

2023-01-19 15:37 UTC, Ga-Mikael approved these changes

2023-01-19 16:16 UTC, sblondeau requested changes

2023-01-19 16:16 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            $interactions = $decision->getInteractions()->toArray();
pourquoi le toArray() ? ça ne marche pas le foreach direction sur $interactions en tant que Collection ?

2023-01-19 16:16 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            foreach (array_count_values($interactionUsers) as $userIteration) {
à la reflexion tu dois pouvoir utiliser la validation Unique au niveau de ton entity 
https://symfony.com/doc/current/reference/constraints/Unique.html
ça va t'éviter de faire tout la logique ici

2023-01-19 16:16 UTC, sblondeau commented on src/Form/InteractionType.php
> +                        Interaction::DECISION_IMPACTED => Interaction::DECISION_IMPACTED,
tu dois pas enlever le decisionRole du form plutot ?

2023-01-19 20:09 UTC, V-Gillet commented on src/Controller/DecisionController.php
> +            foreach (array_count_values($interactionUsers) as $userIteration) {
ça ne marche pas sur le champ interaction de l'entité Decision et je ne peux pas le mettre sur le champ user d'Interaction car un User peut être impacté sur plusieurs décisions.

2023-01-19 20:11 UTC, V-Gillet commented on src/Controller/DecisionController.php
> +            $interactions = $decision->getInteractions()->toArray();
Effectivement, ça fonctionne sans

2023-01-19 20:13 UTC, V-Gillet commented on src/Form/InteractionType.php
> +                        Interaction::DECISION_IMPACTED => Interaction::DECISION_IMPACTED,
J'y ai pensé mais je me suis dit que ce serait plus facile à gérer comme ça. Sinon j'aurais dû avoir 2 CollectionType d'Interactions et je ne sais pas comment le faire fonctionner

2023-01-20 15:10 UTC, ByZirTox approved these changes

2023-01-20 16:05 UTC, Ga-Mikael approved these changes

2023-01-20 18:04 UTC, sblondeau approved these changes

2023-01-20 18:04 UTC, merged