Comment the first Decision
WildCodeSchool/202209-orleans-php-project-makesense pull request #231
Opened 2023-01-20 13:00 UTC by ByZirTox

2023-01-20 14:24 UTC, V-Gillet requested changes

2023-01-20 14:24 UTC, V-Gillet commented on templates/decisions/commentView.html.twig
> +	{{ encore_entry_link_tags('decisionView') }}
tu utilises le fichier scss de decisionView

2023-01-20 14:36 UTC, V-Gillet approved these changes

2023-01-23 10:10 UTC, sblondeau requested changes

2023-01-23 10:10 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            $commentRepository->save($comment, true);
manque pas une redirection là ?

2023-01-23 10:10 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            $comment->setInteraction($interaction);
les set devraient se faire si le form isValid uniquement ?

2023-01-23 10:10 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            $comment->setInteraction($interaction[0]);
tu es sensé récup une seule interaction ? donc peut etre un findOneBy au dessus et non un findBy

2023-01-24 16:31 UTC, V-Gillet submitted a review, later dismissed

2023-01-25 08:15 UTC, sblondeau requested changes

2023-01-25 08:15 UTC, sblondeau commented on src/Form/CommentType.php
> +                'label' => 'Détails de la décision',
le label est pas bon non ?

2023-01-25 08:15 UTC, sblondeau commented on templates/decisions/commentView.html.twig
> +						{{ form_label(commentForm.comment, ' ') }}
ah non là tu l'enlèves le label, faut le laisser et mettre qq chose comme "Laisser un commentaire"

2023-01-25 08:41 UTC, V-Gillet approved these changes

2023-01-25 09:05 UTC, sblondeau approved these changes

2023-01-25 09:30 UTC, V-Gillet approved these changes

2023-01-25 09:34 UTC, merged