S04US18-See_my_impacting_decisions
WildCodeSchool/202209-orleans-php-project-makesense pull request #243
Opened 2023-01-22 15:51 UTC by V-Gillet

2023-01-22 18:50 UTC, Ga-Mikael approved these changes

2023-01-22 18:53 UTC, Ga-Mikael approved these changes

2023-01-23 10:19 UTC, sblondeau requested changes

2023-01-23 10:19 UTC, sblondeau commented on templates/dashboard/index.html.twig
>  							{% include "components/_decisionCards.html.twig" %}
plutot que de devoir set une variable avec le bon nom juste pour ton include, tu peux faire qqu chose comme
{% include "components/_decisionCards.html.twig" with {'decision': interaction.decision} %}

2023-01-23 11:01 UTC, V-Gillet commented
J'ai pull dev sur cette branche par pure inattention...

2023-01-23 11:14 UTC, ByZirTox approved these changes

2023-01-23 11:55 UTC, sblondeau approved these changes

2023-01-23 11:55 UTC, merged