made edit for decisions
WildCodeSchool/202209-orleans-php-project-makesense pull request #249
Opened 2023-01-22 17:37 UTC by V-Gillet

2023-01-22 18:56 UTC, Ga-Mikael submitted a review, later dismissed

2023-01-23 08:12 UTC, Ga-Mikael submitted a review, later dismissed

2023-01-23 10:22 UTC, sblondeau requested changes

2023-01-23 10:22 UTC, sblondeau commented on src/Controller/DecisionController.php
> +            if ($decision->getDecisionStartTime() !== $decisionStartTime) {
ça marche mais ce n'est pas la bonne façon de faire
- il faudrait que tu rendes la date de création non modifiable dans le cas d'un edit (donc un form différent)
- créé un DecisionEditionType qui extend DecisionCreationType, et tu fais juste un $builder->remove('startTime'))

2023-01-24 16:52 UTC, ByZirTox approved these changes

2023-01-25 08:25 UTC, sblondeau requested changes

2023-01-25 08:25 UTC, sblondeau commented on src/Controller/DecisionController.php
> +        $form = $this->createForm(DecisionEditionType::class, $decision);
comme tu l'as fais pour l'affichage du bouton "modifier", il faut que tu check aussi ici si l'user en cours est bien celui qui a créé la décision, sinon erreur 403

Le mieux serait de passer par un voters https://symfony.com/doc/current/security/voters.html
(tu as de mémoire un make:voter de dipso, regarde rapidement la doc c'est pas très compliqué ;-) )

2023-01-25 08:25 UTC, sblondeau commented on src/Form/DecisionEditionType.php
> +    public function buildForm(FormBuilderInterface $builder, array $options): void
pour la lisibilité, laisse le buildForm en 1ere méthode dans ta classe

2023-01-25 08:35 UTC, ByZirTox submitted a review, later dismissed

2023-01-25 09:06 UTC, sblondeau requested changes
voters à faire

2023-01-25 10:10 UTC, ByZirTox approved these changes

2023-01-25 10:53 UTC, sblondeau requested changes

2023-01-25 10:53 UTC, sblondeau commented on src/Security/DecisionVoter.php
> +        /** @var Decision $post */
$decision pas $post

2023-01-25 10:53 UTC, sblondeau commented on src/Security/DecisionVoter.php
> +    private const VIEW = 'view';
tu t'en sers par du VIEW, tu compte t'en servir après ? sinon retire

2023-01-25 11:12 UTC, ByZirTox approved these changes

2023-01-25 11:56 UTC, sblondeau approved these changes

2023-01-25 20:38 UTC, Ga-Mikael approved these changes

2023-01-26 07:03 UTC, merged