S02 us28 voir catégory
WildCodeSchool/202209-orleans-php-project-makesense pull request #270
Opened 2023-01-24 20:47 UTC by stephaparicio

2023-01-25 09:33 UTC, ByZirTox reviewed
Tu a 2 fichier categoryType identique garde en que 1

2023-01-25 09:36 UTC, ByZirTox commented on templates/admin/index.html.twig
> +{% block title %}Hello AdminController!{% endblock %}
Traduit toute la view en FR

2023-01-25 09:36 UTC, ByZirTox commented on templates/admin_category/edit.html.twig
> +{% block title %}Edit Category{% endblock %}
Idem a traduire

2023-01-25 09:36 UTC, ByZirTox commented on templates/admin_category/new.html.twig
> +{% extends 'base.html.twig' %}
Traduction

2023-01-25 09:36 UTC, ByZirTox commented on templates/admin_category/show.html.twig
> +                    <th scope="row">Primary</th>
Traduction

2023-01-25 09:36 UTC, ByZirTox commented on templates/category/index.html.twig
> +{% extends 'base.html.twig' %}
Idem la traduction

2023-01-25 09:36 UTC, ByZirTox commented on tests/Controller/CategoryControllerTest.php
> +<?php
Pas sur que tout functionne pour ton crud ont testera ensemble voir si tout marche bien (Le edit, le new, et le delete)

2023-01-30 13:32 UTC, ByZirTox approved these changes

2023-01-30 13:37 UTC, sblondeau requested changes
et il manque les Assert sur l'entity Category

2023-01-30 13:37 UTC, sblondeau commented on templates/admin_category/_delete_form.html.twig
> +<form method="post" action="{{ path('app_admin_category_delete', {'id': category.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir suprimer');">
orthographe
"Êtes vous sûr de vouloir supprimer ?"

2023-01-30 13:37 UTC, sblondeau commented on templates/admin_category/_form.html.twig
> +    <button class="btn">{{ button_label|default('Save') }}</button>
traduire le "Save"

2023-01-30 13:37 UTC, sblondeau commented on src/Form/CategoryType.php
> +            ->add('name')
traduire les labels

2023-01-30 13:47 UTC, ByZirTox approved these changes

2023-01-30 13:47 UTC, ByZirTox submitted a review, later dismissed

2023-01-30 14:08 UTC, sblondeau requested changes

2023-02-04 21:04 UTC, V-Gillet requested changes

2023-02-04 21:04 UTC, V-Gillet commented on symfony.lock
> -    "myclabs/deep-copy": {
Il faut que je vois avec Sylvain si avoir touché à phpunit et les fichiers de configuration de symfony ne casse pas le projet

2023-02-07 14:24 UTC, closed without merging