US42S04 - Visualization of the comments.
WildCodeSchool/202209-orleans-php-project-makesense pull request #281
Opened 2023-01-26 10:23 UTC by Ga-Mikael

2023-01-26 13:03 UTC, KevynSola submitted a review, later dismissed

2023-01-26 13:11 UTC, ByZirTox approved these changes

2023-01-26 14:57 UTC, sblondeau requested changes

2023-01-26 14:57 UTC, sblondeau commented on src/Controller/DecisionController.php
> +use Proxies\__CG__\App\Entity\Decision as EntityDecision;
pb là dans ton use

2023-01-26 14:57 UTC, sblondeau commented on templates/decisions/commentView.html.twig
> +			{% for commentsFirstPeriod in commentsFirstPeriods %}
fait un include qui contient toute cette boucle for, en passwant dans le "with" comments et bg-color
ça simplifiera au moins un peu

2023-01-27 07:57 UTC, V-Gillet submitted a review, later dismissed

2023-01-27 08:37 UTC, sblondeau approved these changes

2023-01-27 09:32 UTC, sblondeau approved these changes

2023-01-27 09:32 UTC, merged