Fix- admin user style
WildCodeSchool/202209-orleans-php-project-makesense pull request #289
Opened 2023-01-26 15:14 UTC by Ga-Mikael

2023-01-26 16:27 UTC, ByZirTox approved these changes

2023-01-27 07:07 UTC, sblondeau requested changes

2023-01-27 07:07 UTC, sblondeau commented on templates/admin_user/edit.html.twig
> +				<form method="post" action="{{ path('app_admin_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
trad

2023-01-27 07:07 UTC, sblondeau commented on templates/admin_user/_form.html.twig
>  {{ form_label(form.email, 'Email')}}
quelle plus value par rapport à des form_row ?

2023-01-27 08:50 UTC, ByZirTox submitted a review, later dismissed

2023-01-27 09:22 UTC, ByZirTox approved these changes

2023-01-27 09:33 UTC, sblondeau approved these changes

2023-01-27 09:33 UTC, merged