US69SO05 - Error 404 and 401 pages
WildCodeSchool/202209-orleans-php-project-makesense pull request #309
Opened 2023-01-30 09:56 UTC by Ga-Mikael

2023-01-30 10:37 UTC, ByZirTox approved these changes

2023-01-30 12:05 UTC, sblondeau requested changes
et il me faut une page erreur 500 aussi ;-)

2023-01-30 12:05 UTC, sblondeau commented on assets/styles/_theme.scss
> +  1: 18rem,
pas certain de ce que ça fait ça ? tu es sur que ça ne va pas impacté d'autres choses ?

2023-01-30 13:51 UTC, Ga-Mikael commented on assets/styles/_theme.scss
> +  1: 18rem,
Cela impacte seulement la classe display-1 de bootstrap, normalement elle n'est pas utiliser autre part sur notre projet.

2023-02-06 15:49 UTC, V-Gillet approved these changes

2023-02-06 16:02 UTC, sblondeau approved these changes

2023-02-07 04:59 UTC, V-Gillet approved these changes

2023-02-07 08:13 UTC, merged