fix: only impacted and expert employees can ge tin conflict in a deci…
WildCodeSchool/202209-orleans-php-project-makesense pull request #348
Opened 2023-01-31 15:00 UTC by V-Gillet

…sion

2023-01-31 15:07 UTC, ByZirTox submitted a review, later dismissed

2023-01-31 15:18 UTC, sblondeau requested changes

2023-01-31 15:18 UTC, sblondeau commented on src/Controller/DecisionController.php
> +                $this->addFlash('danger', 'Seul les personnes impactées ou expertes peuvent entrer en conflit');
Seules ?

2023-01-31 15:23 UTC, Ga-Mikael submitted a review, later dismissed

2023-02-05 22:13 UTC, sblondeau approved these changes

2023-02-05 22:14 UTC, merged