Fix - Background PageAllDecision
WildCodeSchool/202209-orleans-php-project-makesense pull request #394
Opened 2023-02-06 15:23 UTC by ByZirTox

2023-02-06 15:57 UTC, Ga-Mikael requested changes

2023-02-06 15:57 UTC, Ga-Mikael commented on assets/styles/_theme.scss
> +    height: 100;
Pas d'unité ?

2023-02-06 15:57 UTC, Ga-Mikael commented on templates/decisions/allDecisions.html.twig
> +	<main class="min-vh-100 bg-primary pb-5">
Tu la set ou cette classe ?

2023-02-07 08:31 UTC, ByZirTox commented on templates/decisions/allDecisions.html.twig
> +	<main class="min-vh-100 bg-primary pb-5">
Boostrap :D

2023-02-07 11:29 UTC, V-Gillet approved these changes

2023-02-07 11:34 UTC, sblondeau submitted a review, later dismissed

2023-02-07 16:52 UTC, sblondeau approved these changes

2023-02-07 16:52 UTC, merged