titre décisions
WildCodeSchool/202209-orleans-php-project-makesense pull request #76
Opened 2022-12-14 23:06 UTC by stephaparicio

2022-12-15 13:15 UTC, V-Gillet submitted a review, later dismissed

2022-12-15 14:56 UTC, sblondeau requested changes

2022-12-15 14:56 UTC, sblondeau commented on templates/home/index.html.twig
> +	</a>
a reprendre, tous les liens sont cassés là ! 
il faut bien que tu es un lien englobant chaque h2
là tu as des liens qui s'ouvrent et se ferment juste après, ou imbriqués les uns dans les autres...

2022-12-16 08:29 UTC, Zakari-B requested changes
Le template avis (et son fichier avis.html.twig qui est vide), n'ont je pense pas de lie navec cette US. A supprimer.

2022-12-16 08:29 UTC, Zakari-B commented on assets/styles/_theme.scss
> +    font-size: 20px;
Pour des questions d'accessibilité on ne mets jamais les tailles de police en pixels, toujours en rem.

2022-12-16 08:29 UTC, Zakari-B commented on assets/styles/_theme.scss
> +    font-size: 270px;
Même remarque que précédemment.

2022-12-16 08:29 UTC, Zakari-B commented on assets/styles/_theme.scss
> +    font-size: 50px;
Et là aussi.

2022-12-16 08:29 UTC, Zakari-B commented on templates/home/index.html.twig
> +		<h2 class="recherche  px-5 fw-bolder "><a href="#fini" class = " text-decoration-none text-light" >Les Décisions bientôt finies</a>
Pas de majuscule a décisions.

2022-12-16 08:29 UTC, Zakari-B commented on templates/home/index.html.twig
> +		<h2 class="recherche text-light px-5 fw-bolder "><a href="#recent" class = " text-decoration-none text-light">Les Décisions récement terminée</a>
Ici non plus, et deux m à récemment, terminées au pluriel.

2022-12-16 08:29 UTC, Zakari-B commented on templates/home/index.html.twig
> +			Les Décisions bientôt finies
Décisions avec une minuscule, pareil en dessous (et récemment avec deux m encore une fois pour en dessous).

2022-12-16 08:32 UTC, Zakari-B requested changes

2022-12-16 08:32 UTC, Zakari-B commented on templates/home/index.html.twig
> +			<label class="recherche text-light col-sm-2 col-form-label">
Il est lié à quoi ce label ..?

2022-12-16 09:43 UTC, ByZirTox submitted a review, later dismissed

2022-12-16 09:46 UTC, V-Gillet submitted a review, later dismissed

2022-12-16 10:15 UTC, Zakari-B requested changes

2022-12-16 10:15 UTC, Zakari-B commented on templates/home/index.html.twig
> +				<h2 class="fw-bolder recherche text-light col-sm-2 ">Recherche</h2>
Tu utilises la classe recherche 6 fois dans ce fichier mais elle n'existe pas dans le CSS. A supprimer donc.

2022-12-16 10:19 UTC, V-Gillet approved these changes

2022-12-16 10:36 UTC, Zakari-B approved these changes

2022-12-16 10:36 UTC, merged