Sp01 us01 page Login
WildCodeSchool/202209-orleans-php-project-makesense pull request #86
Opened 2022-12-15 13:55 UTC by ByZirTox

2022-12-15 14:59 UTC, V-Gillet requested changes

2022-12-15 14:59 UTC, V-Gillet commented on src/Controller/SecurityController.php
> +        $error = $authenticationUtils->getLastAuthenticationError();
Pas d'abréviation, et utilisateur c'est français. J'ai déjà fait le coup à Sylvain, mieux vaut pas le refaire :D

2022-12-15 15:01 UTC, ByZirTox commented on src/Controller/SecurityController.php
> +        $error = $authenticationUtils->getLastAuthenticationError();
C'est symfony qui ma générée cela

2022-12-15 15:26 UTC, sblondeau commented on templates/security/login.html.twig
> +				You are logged in as
traduction

2022-12-15 16:29 UTC, V-Gillet approved these changes

2022-12-16 10:11 UTC, Zakari-B requested changes
A refaire en symfony 6.x plutôt que 5.2.

2022-12-16 10:51 UTC, Zakari-B requested changes
RegistrationController est à effacer.

2022-12-16 10:51 UTC, Zakari-B commented on src/DataFixtures/UserFixtures.php
> +        $user->setEmail('admin@make-sence.ms');
MakeSense pas Sence, pareil pour le Lastname de l'admin.

2022-12-16 10:56 UTC, Zakari-B approved these changes

2022-12-16 10:57 UTC, merged